DIT113-V22/group-12

arduino/smartcar/smartcar.ino
I have implemented a basic obstacle avoidance feature, where ultrasonic sensor reads data in front of the car. If there is any value above 0, that is received in the sensor, then the car stops. Otherwise it starts driving by itself.
=> Obstacle avoidance feature implementation

arduino/smartcar/smartcar.ino
Implemented manual control of the smartcar
=> Add car manual control via serial input

CarEshipApp/app/src/main/java/com/example/careshipapp/DBHelperClass.java, CarEshipApp/app/src/main/java/com/example/careshipapp/MainActivityCreateAccount.java, CarEshipApp/app/src/main/java/com/example/careshipapp/MainActivityLoginPage.java, CarEshipApp/app/src/main/res/layout/activity_main_login_page.xml, CarEshipApp/local.properties
Implemented the database for logging in and creating an account.
=> Users login database, first draft

CarEshipApp/app/src/main/AndroidManifest.xml, CarEshipApp/app/src/main/java/com/example/careshipapp/DBHelperClass.java, CarEshipApp/app/src/main/java/com/example/careshipapp/MainActivityCreateAccount.java, CarEshipApp/app/src/main/java/com/example/careshipapp/MainActivityLoginPage.java
When creating an account, credentials did not insert into the users table. Also fixed attributes, and logic.
=> Fixed bug: credentials are not inserted

CarEshipApp/app/build.gradle, CarEshipApp/app/src/main/AndroidManifest.xml, CarEshipApp/app/src/main/java/com/example/careshipapp/MqttClient.java, CarEshipApp/local.properties, CarEshipApp/settings.gradle
adding MqttClient on android package
=> Add Mqttclient

README.md
Adding "Our progress" title and the demo of the first Sprint to the readme file, so that the Product Owner can see our progress during this Sprint, and the next Sprints to come.
=> Adding "Our progress" title and the demo of the first Sprint 

CarEshipApp/app/src/main/AndroidManifest.xml, CarEshipApp/app/src/main/java/com/example/careshipapp/CarControl/JoystickFunctionality.java, CarEshipApp/app/src/main/java/com/example/careshipapp/CarControl/JoystickMainActivity.java, CarEshipApp/app/src/main/java/com/example/careshipapp/CarControl/MqttClient.java, CarEshipApp/app/src/main/res/layout/joystick_main_activity.xml, CarEshipApp/local.properties
Implemented functional GUI for the joystick, so that the staff member can move it 360 degrees around both X and Y axes. Also created a package called "CarControl" in order to group classes that might be coupled together in the future implementations.
=> Created GUI for the joystick.

CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/OrderConfirmation.java, CarEshipApp/app/src/main/res/layout/order_confirmation.xml, CarEshipApp/app/src/main/res/layout/track_order.xml, CarEshipApp/local.properties
customer order date for the order confirmation screen
=> order date

.github/workflows/arduino-build.yml
Adding MQTT library to the Arduino CI workflow.
=> Updated Arduino CI workflow with MQTT library

arduino/smartcar/smartcar.ino
First draft implementation of the Arduino smartcar's connection to the MQTT broker. So far It receives publishing commands from the terminal, and is able to publish front distance sensor data back to the terminal.
=> Implementation of Arduino smartcar connection to MQTT broker. Re-entry.

CarEshipApp/.gitignore, CarEshipApp/local.properties
I have created a gitignore file to prevent the consistent issue about sdk directory path.
=> Android .gitignore file

CarEshipApp/app/build.gradle, CarEshipApp/app/src/main/AndroidManifest.xml, CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickFunctionality.java, CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickMainActivity.java, CarEshipApp/build.gradle, CarEshipApp/gradle.properties
Implemented MQTT connection on android app side, so that now the car can drive forward, stop, turn in different directions, and drive back using the app's joystick.
=> Android-side MQTT implementation

CarEshipApp/app/src/main/AndroidManifest.xml, CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/OrderConfirmation.java, CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/TrackOrder.java, CarEshipApp/app/src/main/res/layout/track_order.xml
Added estimated time of delivery for customer track order
=> Estimated time of delivery

CarEshipApp/app/src/main/AndroidManifest.xml, CarEshipApp/app/src/main/java/com/example/careshipapp/customer_gui/ListOrders.java, CarEshipApp/app/src/main/res/layout/activity_list_orders.xml
adding the first edition of how the order list on the staff side supposed to look like.
=> Add order list

.github/workflows/android.yml
Added the proposed updates on the Android CI to enable the access of the google service repository secret.
=> Android CI update with google secret access job.

arduino/smartcar/smartcar.ino
Arduino-side camera implementation for the staff member joystick screen.
=> Camera implementation Arduino

CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickMainActivity.java, CarEshipApp/app/src/main/res/layout/joystick_main_activity.xml, CarEshipApp/app/src/main/res/values/strings.xml
Implementation of the camera in the Android app.
=> Android-side camera implementation

CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickFunctionality.java, CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickMainActivity.java
It is now possible to accelerate and decelerate the car based on the position of the joystick.
=> Implementation of acceleration and deceleration of the car.

CarEshipApp/app/src/main/java/com/example/careshipapp/car_control/JoystickMainActivity.java, CarEshipApp/app/src/main/res/layout/joystick_main_activity.xml, CarEshipApp/app/src/main/res/values/ids.xml, CarEshipApp/app/src/main/res/values/strings.xml
Implementation of toggle switch button, that activates or deactivates autopilot on the smart car.
=> Implementation of autopilot toggle switch button.

CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/ShowAllActivity.java, CarEshipApp/app/src/main/java/com/example/careshipapp/gui/adapters/ShowAllAdapter.java, CarEshipApp/app/src/main/res/layout/activity_show_all.xml, CarEshipApp/build.gradle
This search filter optimises user experience while going through products
=> Adding the search filter

careship-mod/CarEship.gd
=> CarEship-mod-files

arduino/smartcar/smartcar.ino
Implementation of autopilot driving on the Arduino side. When autopilot mode is switched on, the car is able to turn right if there is an obstacle at the front. If there is an obstacle at the front and right, then the car turns left. If there is an obstacle at the front and left, then the car turns right.
=> Autopilot driving Arduino implementation

README.md
Adding Retrospective 1 and 2 so that our PO is able to see our planning and progress in terms of these sprints.
=> Adding Retrospective 1 and 2

README.md
Added an updated problem description field, and updated the tools with Espresso testing.
=> Added an updated problem description

README.md
Changed demo 1 and 2 display pngs to gifs
=> Changed demos display

README.md
attempt to fix the sprints demos gifs being unclickable
=> sprint demo videos gifs bug solve attempt

README.md
=> Added links to demo sprints video to README.md

arduino/smartcar/smartcar.ino
- Changed from infrared sensors to ultrasound sensors, in order to get a greater distance to obstacles on the sides
- Changed logic of the autopilot method
- Refactored the code
=> Left and right sensors obstacle avoidance implementation.

arduino/smartcar/board_config.json, arduino/smartcar/vehicle_config.json
The json configuration files for ultrasound sensors, so that upon cloning of the repository the sensors in the smartcar.ino file are able to function.
=> Board and vehicle sensor configuration files

.github/workflows/android.yml
I want to test if we can use the Android Ci to integrate the tests and if possible generate tests reports.
=> Android CI update for tests

CarEshipApp/app/build.gradle, CarEshipApp/app/src/main/java/com/example/careshipapp/gui/activities/CustomerPaymentActivity.java, CarEshipApp/app/src/main/res/layout/activity_main_login_page.xml, CarEshipApp/app/src/main/res/layout/order_confirmation.xml, CarEshipApp/app/src/main/res/layout/staff_login_page.xml
=> Enabled password show/hide in login screens
